### ISSUE TITLE
Issue with Firefox and Mobile

### ISSUE THREAD

**Issue by vklap** [twhitbeck/angular-cropper#1]
Hi Tim,

Thanks for this nice cropper - really easy to implement :)

I've had 2 issues:
1. Firefox on desktop: the canvas is not always being filled (especially not after the first attempt to select a file).
2. I've tried it on my mobile device (Samsung S4 - Chrome) - and the image inside the canvas cannot be moved.

It would be great if you could fix it.

Thanks,
Victor

**Comment by twhitbeck** [comment]
Hi Victor,

Thanks for the issue. I've pushed a couple modifications. Can you try again with the latest version from the repo? If it fixes the issues, I'll push a new release to bower.

**Comment by vklap** [comment]
Hi Tim,

Thank you so much. 

The first issue (FF on desktop) works like a charm :)

The second one (Chrome on Samsung S4 mobile device) - still doesn't work.
Supporting image cropping on mobile devices is less important for me, yet if you decide to fix it as well, I'll be more than happy to test it.

Again, thanks a lot - it's really awesome.

Have a great day,
Victor
