### ISSUE TITLE
Only zoom in on wheel any direction

### ISSUE THREAD

**Issue by alnimu** [twhitbeck/angular-cropper#3]
In Google Chrome 44 image only zoom in on wheel event. When I logged event, there wasn't deltaY property, but in originalEvent was.

Works correctly only if change line:
if (e.deltaY < 0) {

to

if (e.originalEvent.deltaY < 0) {

**Comment by twhitbeck** [comment]
I'm not sure I understand the problem. Your image isn't zooming when you scroll your mouse wheel? Please share some more info. Thanks

**Comment by alnimu** [comment]
First I load an image, then when I scroll the wheel (there is no difference scroll down or scroll up), the image zooms out, when it reaches max zoom I can only drag the image. It happens because in scroll event there is no property deltaY.
![wheel_1](https://cloud.githubusercontent.com/assets/3279678/9037951/fba72f50-39f8-11e5-9cd7-38b3efda8d78.jpg)
![wheel_2](https://cloud.githubusercontent.com/assets/3279678/9037952/fba7fd22-39f8-11e5-84dd-e79407e694d2.jpg)

**Comment by twhitbeck** [comment]
You say when it reaches max zoom. If it's max zoom, what are you expecting the mouse wheel to do? I'll be in gitter for a bit, can you join to explain it to me more?
https://gitter.im/twhitbeck/angular-cropper

**Comment by twhitbeck** [comment]
Ok, issue has been resolved. If jQuery is present, the event does not have `deltaY` which we use. In this case we must use `e.originalEvent.deltaY`. Please update.
