### ISSUE TITLE
Some images are saved as transparent

### ISSUE THREAD

**Issue by vklap** [twhitbeck/angular-cropper#6]
Hi Tim,

Some images are saved as "transparent" images - when not using Chrome.
It can be reproduced on FireFox. I haven't tried other browsers.

It would be great if you could solve this.
Thanks,
Victor

**Comment by twhitbeck** [comment]
@vklap can you show me some code which reproduces this error?

**Comment by vklap** [comment]
Hi Tim,

Thank you so much for responding.

The code is part of a bigger project, which unfortunately I can't share.
However, I can send you a problematic image.
The image is also confidential (it's the face of a person).

Maybe I can send it to you by email?
Thanks,
Victor

**Comment by twhitbeck** [comment]
Yes, let's take this discussion to email. Find mine in my profile.

**Comment by twhitbeck** [comment]
Actually same as #2 only Firefox throws an error which prevents anything from showing.
